server:
  tomcat:
    ## tomcat最大线程数，默认为200  
    max-threads: 1000
    uri-encoding: UTF-8
    min-spare-threads: 30
  connection-timeout: 5000ms
  servlet:
    context-path: /

spring:
  application:
    name: learn-note-job
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    #静态文件配置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  # 404交给异常处理器处理
    add-mappings: false
  # 404交给异常处理器处理
  mvc:
      throw-exception-if-no-handler-found: true
        
        
logging:
  config: classpath:log/logback-spring.xml
  


# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.center.pojo
  #原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl