mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml##resource下配置
  #mapper-locations: classpath:/cn/center/mapper/*.xml
  typeAliasesPackage: cn.center.pojo
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'