# 开发环境配置
server:
  port: 7016
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: ware-click-house
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# mybatis 配置
mybatis:
  type-aliases-package: com.click.house.entity
  mapper-locations: classpath:/mapper/*.xml

#mybatis
mybatis-plus:
  mapper-locations: classpath*:cn/center/*Mapper.xml
  # 内置项目中所有实体扫描包路径
  typeAliasesPackage: cn.center.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:  
   #刷新mapper 调试神器
   refresh: true
   db-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: auto
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: not_empty
    #驼峰下划线转换
    db-column-underline: true    
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #数据库类型
    db-type: mysql
   #自定义SQL注入器
   #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
   #自定义填充策略接口实现
   #meta-object-handler: com.baomidou.springboot.xxx


# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 